package eg.edu.cu.csds.icare.core.ui.theme

import androidx.compose.ui.unit.dp

val XL5_PADDING = 90.dp
val XL4_PADDING = 70.dp
val XL3_PADDING = 60.dp
val XL2_PADDING = 50.dp
val XL_PADDING = 40.dp
val L_PADDING = 20.dp
val M_PADDING = 16.dp
val S_PADDING = 10.dp
val XS_PADDING = 6.dp
val U_PADDING = 2.dp
val ZERO_DIMENSION = 0.dp

val PAGING_INDICATOR_WIDTH = 12.dp
val PAGING_INDICATOR_SPACING = 8.dp

val LANGUAGE_CARD_HEIGHT = 170.dp
val CATEGORY_BOX_WIDTH = 150.dp
val CATEGORY_BOX_HEIGHT = 80.dp
val BORDER_STROKE_SIZE = 1.dp
val THICK_BORDER_STROKE_SIZE = 2.dp
val DOUBLE_THICK_BORDER_STROKE_SIZE = 4.dp

val SPLASH_LOGO_SIZE = 250.dp
val HEADER_ICON_SIZE = 50.dp
val ACTION_BUTTON_SIZE = 45.dp
val ACTION_BUTTON_ICON_SIZE = 30.dp
val HEADER_PROFILE_CARD_WIDTH = 230.dp
val PROFILE_ICON_SIZE = 85.dp
val CATEGORY_ICON_SIZE = 35.dp
val SUB_SERVICE_ICON_SIZE = 35.dp
val MEDIUM_ICON_SIZE = 25.dp

val LOGO_WIDTH = 240.dp
val LOGO_HEIGHT = 80.dp
val SOCIAL_ICON_SIZE = 40.dp

val LABEL_MIN_WIDTH = 100.dp
val BUTTON_WIDTH = 100.dp
val BUTTON_HEIGHT = 60.dp
val BIG_IMAGE_SIZE = 210.dp
val MEDIUM_IMAGE_SIZE = 160.dp
val BOARDER_SIZE = 2.dp
val SETTINGS_ITEM_HEIGHT = 45.dp
val IMAGE_HEIGHT = 500.dp
val SMALL_SPINNER_WIDTH = 120.dp
val LARGE_SPINNER_WIDTH = 280.dp
val BOTTOM_SHEET_HEIGHT = 600.dp
val DIALOG_CARD_HEIGHT = 200.dp
val SOCIAL_BUTTON_WIDTH = 120.dp
