#Kotlin
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3G -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=1 -XX:ReservedCodeCacheSize=320m -XX:+HeapDumpOnOutOfMemoryError
kotlin.build.report.enabled=false
kotlin.build.report.output=file

#Gradle
org.gradle.jvmargs= -Xmx4G -Dfile.encoding=UTF-8 -XX:+UseG1GC -XX:SoftRefLRUPolicyMSPerMB=1 -XX:ReservedCodeCacheSize=256m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.configuration-cache=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache.parallel=true

#Android
android.nonTransitiveRClass=true
android.useAndroidX=true
