[versions]
agp = "8.8.1"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.29"
appcompat = "1.7.0"
coreKtx = "1.15.0"
junit = "4.13.2"
robolectric = "4.14.1"
truth = "1.4.4"
mockito = "5.2.0"
mockWebServer = "5.0.0-alpha.14"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.0"
constrainLayout = "1.1.0"
navigationCompose = "2.8.7"
composeBom = "2025.02.00"
coilCompose = "2.7.0"
appUpdates = "2.1.0"
androidxBrowser = "1.8.0"
multidex = "2.0.1"
koinBom = "4.0.2"
koinKSP = "1.4.0"
splashScreen = "1.0.1"
coroutine = "1.10.1"
ktxSerialization = "1.8.0"
firebaseBom = "33.9.0"
timber = "5.0.1"
retrofit = "2.11.0"
ktxSerConverter = "1.0.0"
okhttp3 = "4.12.0"
room = "2.6.1"
crypto = "1.1.0-alpha06"
sqlcipher = "4.5.4"
safetynet = "18.1.0"
integrity = "1.4.0"
jose4j = "0.9.6"
rootbeer = "0.1.0"
workManager = "2.10.0"
ktlint = "12.1.2"
detekt="1.23.7"
googleServices = "4.4.2"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
appcompat-resources = { module = "androidx.appcompat:appcompat-resources", version.ref = "appcompat" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
androidx-compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
compose-runtime = { group = "androidx.compose.runtime", name = "runtime" }
compose-animation = { group = "androidx.compose.animation", name = "animation" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constrainLayout" }
androidx-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coilCompose" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilCompose" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleRuntimeKtx" }
app-update = { module = "com.google.android.play:app-update-ktx", version.ref = "appUpdates" }
androidx-browser = { module = "androidx.browser:browser", version.ref = "androidxBrowser" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koinKSP" }
koin-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinKSP" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-androidx-workmanager = { module = "io.insert-koin:koin-androidx-workmanager" }
koin-androidx-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }
splashScreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreen" }
coroutine-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutine" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "ktxSerialization" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging-ktx" }
firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
work-manager = { module = "androidx.work:work-runtime-ktx", version.ref = "workManager" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "ktxSerConverter" }
retrofit-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp3" }
room = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
security-crypto-ktx = { module = "androidx.security:security-crypto-ktx", version.ref = "crypto" }
sqlcipher = { module = "net.zetetic:android-database-sqlcipher", version.ref = "sqlcipher" }
safetynet = { module = "com.google.android.gms:play-services-safetynet", version.ref = "safetynet" }
play-integrity = { module = "com.google.android.play:integrity", version.ref = "integrity" }
jose4j = { group = "org.bitbucket.b_c", name = "jose4j", version.ref = "jose4j" }
rootbeer = { module = "com.scottyab:rootbeer-lib", version.ref = "rootbeer" }

#Test Libraries
junit = { group = "junit", name = "junit", version.ref = "junit" }
coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutine" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
google-truth = { module = "com.google.truth:truth", version.ref = "truth" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockito" }
mockwebserver = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "mockWebServer" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }

[bundles]
appcompat = ["appcompat", "appcompat-resources"]
compose = ["androidx-activity-compose", "androidx-compose-foundation", "androidx-ui", "androidx-ui-tooling", "androidx-ui-tooling-preview", "androidx-ui-graphics", "compose-runtime", "compose-animation", "androidx-material3", "androidx-constraintlayout", "androidx-navigation"]
koin = ["koin-annotations", "koin-compiler", "koin-androidx-workmanager", "koin-androidx-compose", "koin-androidx-compose-navigation"]
coil = ["coil-compose", "coil-gif"]
firebase = ["firebase-crashlytics", "firebase-messaging", "firebase-auth"]
lifecycle = ["androidx-lifecycle-runtime-ktx", "androidx-lifecycle-process"]
retrofit = ["retrofit", "retrofit-converter", "retrofit-interceptor"]
room = ["room", "room-ktx", "sqlcipher", "security-crypto-ktx"]
security = ["safetynet", "play-integrity", "jose4j", "rootbeer"]
domain-test = ["junit", "coroutines-android", "coroutines-test", "robolectric", "google-truth", "mockito-inline"]
data-test = ["mockito-inline", "google-truth", "mockwebserver"]
app-test = ["androidx-junit", "androidx-espresso-core", "mockito-inline", "google-truth"]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
android-library = { id = "com.android.library", version.ref = "agp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
