name: Run test

on:
  pull_request:
    branches:
      - main

jobs:
  restrict_pr_sources:
    runs-on: ubuntu-latest
    steps:
      - name: Check source branch
        id: source_check
        run: |
          echo "Source branch is: ${{ github.head_ref }}"
          # Allow only branches matching release/<major>.<minor>.<patch>
          if [[ "${{ github.head_ref }}" =~ ^release/[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "✅ Pull request source is a valid release branch."
          else
            echo "::error::❌ PRs to main are only allowed from release/x.y.z branches (e.g., release/1.2.3). Got: ${{ github.head_ref }}"
            exit 1
          fi
  run-tests:
    needs: restrict_pr_sources
    runs-on: ubuntu-latest

    env:
      DEBUG_BASE_URL: ${{ secrets.DEBUG_BASE_URL }}
      RELEASE_BASE_URL: ${{ secrets.RELEASE_BASE_URL }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      WEB_CLIENT_ID: ${{ secrets.WEB_CLIENT_ID }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: 'gradle'

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > release-key.jks

      - name: Grant execution permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew clean testPatientDebugUnitTest testStaffDebugUnitTest